echo "We are trying this practical from linux EC2"
echo "We are from batch-24 and learning git/gihub"
echo "Happy weekend"
echo "Hello batch-24, We are learning git"
echo "Please complete your practicals on daily basis"
echo " i have made changes "
echo " new line added on date 31st"
echo " new brach created"
echo " 1st rebase changes "
echo " 2nd rebase chnages "
echo " cherry-pick 1st commit "